name: Captain Upload API

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        run: |
          echo "Captain API is working"
          echo "Token exists: ${{ secrets.CAPTAIN_TOKEN != '' }}"
